#!/usr/bin/env python3
"""Write ../README.md. Image URLs are absolute so dark/light <picture> sources resolve on the profile page."""
from pathlib import Path

USER = "adityashroff06-code"
RAW = f"https://raw.githubusercontent.com/{USER}/{USER}/main/assets"
OUT = f"https://raw.githubusercontent.com/{USER}/{USER}/output"
GH = f"https://github.com/{USER}"


def pic(dark, light, alt, width=None, height=None, indent=""):
    size = f' width="{width}"' if width else (f' height="{height}"' if height else "")
    return (f'{indent}<picture>\n'
            f'{indent}  <source media="(prefers-color-scheme: dark)" srcset="{dark}">\n'
            f'{indent}  <img alt="{alt}" src="{light}"{size}>\n'
            f'{indent}</picture>')


def asset(name, alt, **kw):
    return pic(f"{RAW}/{name}-dark.svg", f"{RAW}/{name}-light.svg", alt, **kw)


def linked(url, name, alt, **kw):
    # No whitespace inside <a>: GitHub would underline it next to the image.
    compact = "".join(line.strip() for line in asset(name, alt, **kw).splitlines())
    return f'<a href="{url}">{compact}</a>'


PROJECTS = [
    ("EMS-Co-Pilot-", "project-ems", "EMS Co-Pilot: plant energy readings in, traceable energy and carbon reports out. 175,200 duplicate rows caught before reporting."),
    ("YT-Summarizer---Gen-AI-Console", "project-briefing", "GenAI Video Briefing Console: a spoken YouTube video in, a four-part executive brief out."),
    ("Clean_Air_OS", "project-cleanair", "Clean Air OS: an inspectable PM2.5 research baseline for Delhi-area stations, 9,992 validated observations from 9 stations."),
    ("Consumer-Segmentation-and-Purchase-Behavior-Analysis", "project-segmentation", "Consumer Segmentation: K-Means segments of bath-soap households, then three classifiers compared."),
]
# The live cards need .github/workflows/refresh-stats.yml in place (it builds them on the `output` branch).
LIVE_STATS = (Path(__file__).resolve().parent.parent / ".github" / "workflows" / "refresh-stats.yml").exists()
SKILLS = "py,r,js,mysql,sqlite,opencv,sklearn,fastapi,react,vite,git,githubactions,vscode,anaconda"


def build():
    rows = []
    for i in range(0, len(PROJECTS), 2):
        cells = "\n".join(linked(f"{GH}/{repo}", name, alt, width="49%") for repo, name, alt in PROJECTS[i:i + 2])
        rows.append(f'<p align="center">\n{cells}\n</p>')
    def block(inner, align=None):
        a = f' align="{align}"' if align else ""
        return f"<p{a}>\n{inner}\n</p>"

    parts = [
        block(asset("hero", "Aditya Shroff: Digital Transformation and AI Enablement Specialist, now building Sentinel, city-scale CCTV analytics", width="100%")),
        block(linked("https://www.linkedin.com/in/aditya-shroff-8033a31b0/", "pill-linkedin", "Connect on LinkedIn", height="44")
              + "\n&nbsp;\n"
              + linked("mailto:adityashroff06@gmail.com", "pill-email", "Email adityashroff06@gmail.com", height="44"), "center"),
        block(asset("about", "class Aditya: Digital Transformation and AI Enablement Specialist. Focus: computer vision, GenAI and RAG, data engineering. Building Sentinel.", width="100%")),
        "<br>",
        block(linked(f"{GH}/Sentinel_Repo", "sentinel", "Sentinel: one platform over 26 departments' CCTV. Hand it a registration number, get back the vehicle's complete timestamped route.", width="100%")),
        f'<p align="right"><sub>Structured v2 rebuild in progress: <a href="{GH}/sentinel-gujarat"><code>sentinel-gujarat</code></a></sub></p>',
        *rows,
        "<br>",
        block(pic(f"https://skillicons.dev/icons?i={SKILLS}&theme=dark&perline=14", f"https://skillicons.dev/icons?i={SKILLS}&theme=light&perline=14",
                  "Python, R, JavaScript, MySQL, SQLite, OpenCV, scikit-learn, FastAPI, React, Vite, Git, GitHub Actions, VS Code, Anaconda", width="100%"), "center"),
        block(asset("toolbox", "Toolbox: computer vision, GenAI and NLP, data and ML, engineering", width="100%")),
        *(["<br>",
        block(pic(f"{OUT}/stats-dark.svg", f"{OUT}/stats-light.svg", "GitHub pulse: contributions, streaks, commits, pull requests, repositories, stars and top languages over the last 12 months", width="100%")),
        block(pic(f"{OUT}/snake-dark.svg", f"{OUT}/snake-light.svg", "A snake eating the last year of contributions", width="100%"))] if LIVE_STATS else []),
        "<br>",
        block(asset("footer", "Thanks for stopping by", width="100%")),
        block(f'<img alt="Profile views" src="https://komarev.com/ghpvc/?username={USER}&label=profile%20views&color=7c3aed&style=flat-square">', "center"),
    ]
    header = f"""<!--
  Profile README for github.com/{USER}
  - Static cards in ./assets are generated by design/build.py (dark + light, fonts embedded).
  - The GitHub pulse card and the contribution snake are rebuilt daily by
    .github/workflows/refresh-stats.yml and published to the `output` branch.
-->"""
    return header + "\n\n" + "\n\n".join(parts) + "\n"


if __name__ == "__main__":
    path = Path(__file__).resolve().parent.parent / "README.md"
    path.write_text(build(), encoding="utf-8")
    print(f"wrote {path}")
